apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch
            image: gcr.io/{PROJECT_ID}/batch:v1
            imagePullPolicy: Always
            env:
            - name: DB_USER
              value: "user"
            - name: DB_PASS
              value: "pass"
            - name: USER_CONNECTION_NAME
              value: "connection"
            command: ["go","run","/go/src/batch/main.go"]
          restartPolicy: OnFailure
      backoffLimit: 2
